# Generated by Django 3.2.7 on 2021-10-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(upload_to='productImages/')),
                ('productName', models.CharField(max_length=40)),
                ('productDescription', models.TextField()),
                ('productViewed', models.IntegerField()),
                ('productBuyed', models.IntegerField()),
                ('productCompany', models.CharField(max_length=100)),
                ('productPrice', models.IntegerField()),
                ('productDiscount', models.IntegerField()),
                ('productAddedDate', models.DateTimeField(auto_now_add=True)),
                ('productQuantity', models.IntegerField()),
                ('productDiscountedPrice', models.IntegerField()),
                ('avgReview', models.FloatField(default=50)),
                ('noOfReviews', models.IntegerField(default=1)),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoryName', models.CharField(max_length=50)),
                ('subCategoryDiscount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=40)),
                ('userEmail', models.EmailField(max_length=60)),
                ('userPassword', models.CharField(max_length=20)),
                ('userContact', models.CharField(max_length=20)),
                ('userAddedDate', models.DateTimeField(auto_now_add=True)),
                ('userAddress', models.CharField(max_length=200)),
                ('userBuyedProducts', models.ManyToManyField(related_name='userBuyedProducts', to='user_app.Product')),
                ('userCart', models.ManyToManyField(related_name='userCart', to='user_app.Product')),
                ('userProducts', models.ManyToManyField(to='user_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewTitle', models.CharField(max_length=40)),
                ('reviewDesc', models.TextField()),
                ('reviewRating', models.IntegerField()),
                ('reviewAddedDate', models.DateTimeField(auto_now_add=True)),
                ('reviewProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.product')),
                ('reviewUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productSubCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.subcategory'),
        ),
    ]
