# Generated by Django 3.2.7 on 2021-10-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userProducts',
            field=models.ManyToManyField(related_name='userProducts', to='user_app.Product'),
        ),
    ]
