# Generated by Django 3.2.7 on 2021-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_userproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productSubCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='categoryDiscount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
