# Generated by Django 3.2.7 on 2021-10-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20211006_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryDiscount',
        ),
    ]
