# Generated by Django 3.2.7 on 2021-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_category_categorydiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avgReview',
            field=models.FloatField(default=105),
        ),
    ]
