# Generated by Django 3.2.7 on 2021-10-21 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20211021_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='saleAddress',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='salePrice',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
