# Generated by Django 3.2.8 on 2021-10-26 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_auto_20211026_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='saleProduct',
        ),
        migrations.CreateModel(
            name='SelledProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.sales')),
                ('saleProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.product')),
            ],
        ),
    ]
