# Generated by Django 3.2.8 on 2021-10-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_auto_20211026_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='paymentMode',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online Payment', 'Online Payment')], default='Cash On Delivery', max_length=50),
        ),
    ]
