# Generated by Django 3.2.8 on 2021-10-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_sales_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='paymentMode',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online Payment', 'Online Payment')], max_length=50),
        ),
    ]
