# Generated by Django 3.2.8 on 2021-10-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_sales_paymentmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='razorpay_payment_id',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
