# Generated by Django 3.2.8 on 2021-10-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_auto_20211026_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='saleProducts',
            field=models.ManyToManyField(related_name='saleProducts', to='user_app.Product'),
        ),
        migrations.DeleteModel(
            name='SelledProducts',
        ),
    ]
