# Generated by Django 3.2.8 on 2021-10-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_auto_20211026_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='razorpay_signature',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='sales',
            name='razorpay_order_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='razorpay_payment_id',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
